# Header
menu:
  Home: /
  作者: /About-Me
  翰斯小舖: /shop
  自由之路: /Freedom
  台灣語料翰編: https://yltwhans.herokuapp.com
  Cheatsheets: /Cheatsheets
  Archives: /archives
  Projects: /projects

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- tagcloud
- category
# - tag
- archive

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-79725140-1
favicon: /favicon.png
twitter: evilchiang
google_plus:
fb_admins:
fb_app_id:
