# Header
menu:
  Home: /
  作者: /About-Me
  Cheatsheets: /Cheatsheets
  Archives: /archives

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- tweet
- recent_posts
- category
# - tagcloud
# - tag
- archive
# - links

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-79725140-1
favicon: /favicon.png
twitter: evilchiang
google_plus:
fb_admins:
fb_app_id:
